### ISSUE TITLE
"sklearn" dependency

### ISSUE THREAD

**Issue by arokem** [openopt/copt#105]
Hello! Would it be possible to cut a new release soon? The most recent release, version 0.8.4 (from 2020), has ["sklearn" as a dependency](https://github.com/openopt/copt/blob/0.8.4/setup.py#L28), which causes issues for our downstream dependencies when we try to install copt: https://github.com/yeatmanlab/AFQ-Insight/actions/runs/4484579586/jobs/7885232689?pr=138#step:4:577

**Comment by fabianp** [comment]
thanks for flagging this. I've now made a new release, hope that helps.

BTW I'm happy to add you as co-mantainer on pypi if that would help (I'm not actively maintaining this project anymore)
