### ISSUE TITLE
Installation issue in new environment

### ISSUE THREAD

**Issue by richford** [openopt/copt#21]
I'm having trouble installing copt in a new python environment. Steps to reproduce (using conda in bash):

```bash
conda create --name copt-test python=3.6
conda activate copt-test
echo copt > requirements.txt
pip install -r requirements.txt
```

Output:
```
Collecting copt (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/95/00/b7bb95dd4c2310c8113bc54982b2fc33f1c79753110f441e2f7380cfad87/copt-0.6.0.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0s/g8g2r38n4451t0gd0txvzr6r0000gn/T/pip-install-6q1flaok/copt/setup.py", line 1, in <module>
        import copt
      File "/private/var/folders/0s/g8g2r38n4451t0gd0txvzr6r0000gn/T/pip-install-6q1flaok/copt/copt/__init__.py", line 3, in <module>
        from .proxgrad import minimize_PGD, minimize_APGD
      File "/private/var/folders/0s/g8g2r38n4451t0gd0txvzr6r0000gn/T/pip-install-6q1flaok/copt/copt/proxgrad.py", line 2, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/0s/g8g2r38n4451t0gd0txvzr6r0000gn/T/pip-install-6q1flaok/copt/
```

I believe this could be fixed by including numpy and scipy in `setup.py` using the `install_requires` parameter. I will submit a PR to that effect.

**Comment by richford** [comment]
Unfortunately, PR #22 did not resolve this for me. I had to add a `pyproject.toml` file (PEP 517/518) so that the build environment itself had numpy, scipy, etc. This fixed the problem on my end (tested for Python 2.7, 3.5, 3.6). I'll submit another PR for your consideration shortly.

This is my first time using a `pyproject.toml` file so I'll just submit the PR and let you decide if this is the solution that you want.

**Comment by fabianp** [comment]
Thanks! I hadn't heard yet about PEP 517 but I'm happy to include it if it
makes installation easier.
