### ISSUE TITLE
Premature termination with callbacks

### ISSUE THREAD

**Issue by richford** [openopt/copt#24]
## The issue

When I execute `minimize_proximal_gradient` with a `copt.utils.Trace()` callback, I get early termination. For example, when trying to run an updated version of the gradient descent example:
```python
import numpy as np
import copt as cp

# .. construct (random) dataset ..
n_samples, n_features = 1000, 200
np.random.seed(0)
X = np.random.randn(n_samples, n_features)
y = np.random.rand(n_samples)

f = cp.utils.LogLoss(X, y)
step_size = 1. / f.lipschitz

cb_pgd = cp.utils.Trace(f)
result_pgd = cp.minimize_proximal_gradient(
    f.f_grad, np.zeros(n_features), step_size=step_size,
    callback=cb_pgd, tol=0, accelerated=False)

cb_apgd = cp.utils.Trace(f)
result_apgd = cp.minimize_proximal_gradient(
    f.f_grad, np.zeros(n_features), step_size=step_size,
    callback=cb_apgd, tol=0, accelerated=True)
```
This throws no error but the traces `cb_apgd` and `cp_pgd` contain only one element, suggesting that `minimize_proximal_gradient` terminated early.

I think the issue is with [this line](https://github.com/openopt/copt/blob/0d7ef31f29071cba0d2f604fd6f95c1a55c7be47/copt/proximal_gradient.py#L108) in `minimize_proximal_gradient` and may have been introduced in [36d7090b](https://github.com/openopt/copt/commit/36d7090b1fceed0e7574355741c326d081739d5c). To illustrate, the old check would pass
```python
if cb_pgd({"x": np.zeros(n_features), "step_size": 42}) == False:
    print("Early Termination!")
```
with no output. Conversely, the new check is
```python
if cb_pgd({"x": np.zeros(n_features), "step_size": 42}) is None:
    print("Early Termination!")
```
with output `Early Termination!`. So this updated version triggers the `break` in `minimize_proximal_gradient`.

## Suggested Fix

Depends on what the intent is for the callback functions' return values. Currently `copt.utils.Trace()` implicitly returns `None` but `minimize_proximal_gradient` is expecting the callback to return a truthy value. So one could fix this by either **(A)** making `Trace` return a truthy value or by **(B)** changing `minimize_proximal_gradient` to test for
```python
if callback(locals()) is not None:
```
or simply
```python
if callback(locals()):
```

I'm happy to submit a PR with either fix if you can tell me which direction you'd like to go. I can also submit a PR with the updated example above once `Trace()` and `minimize_proximal_gradient` are playing nicely again.

**Comment by fabianp** [comment]
Thanks Adam for reporting this. The intention was to have early termination
if the callback returns False and only in that case.

I think the termination condition in that case should be

if callback(locals()) is False:
  stop

What do you think?

**Comment by richford** [comment]
Sounds good to me. Thanks for clarifying! I'll submit a PR.
