### ISSUE TITLE
lmo name is misleading

### ISSUE THREAD

**Issue by GeoffNN** [openopt/copt#28]
In the L1ball, the lmo in update_direction is solving $\max_s \langle s,u\rangle$ instead of $\min_s \langles,u\rangle$. The name and docs are incoherent with the code.
The functions in frank_wolfe.py use lmo(-grad), consistent with this remark.

**Comment by fabianp** [comment]
Can you provide a pull requests fixing this mismatch?

Thanks

**Comment by fabianp** [comment]
hey @GeoffNN , is this still the case and if so can you submit a pull request for this?

**Comment by GeoffNN** [comment]
Working on it
