### ISSUE TITLE
SFW very slow

### ISSUE THREAD

**Issue by fabianp** [openopt/copt#46]
The example https://storage.googleapis.com/copt-doc/auto_examples/plot_sfw.html#sphx-glr-auto-examples-plot-sfw-py currently takes 37 minutes to run, that is way too slow. Ideally it should run under 5 minutes.

I think the example is fine, and the issue is in the SFW implementation, that could be made faster. I propose the following TODO:

1. Profile minimize_sfw to find the bottlenecks
2. Figure strategies to make it faster. For example, batching and/or jit'ing the relevant parts using JAX or numba

**Comment by GeoffNN** [comment]
Just saw this. I'll check this out and try to make it faster.

**Comment by fabianp** [comment]
I strongly recommend the [line_profiler](https://github.com/pyutils/line_profiler) if you haven't used it

**Comment by GeoffNN** [comment]
It seems the bottlenecks are the following two lines:
` p = A[idx].dot(x)`
`grad_agg = utils.safe_sparse_add(grad_agg, (dual_var[idx] - dual_var_prev) * A[idx])`

accounting for resp. 20% of the computation, and 45% of the computation.
I really don't get the second one: `dual_var[idx] - dual_var_prev` is a scalar, so this line should really be faster than the other. Splitting the line in two (sparse_add on one line, and `(dual_var[idx] - dual_var_prev) * A[idx])` on the other shows the bottleneck is the latter.

**Comment by fabianp** [comment]
That's surprising! I also don't get why the dual car line is slower

**Comment by GeoffNN** [comment]
Note that the * in `(dual_var[idx] - dual_var_prev) * A[idx]` is a matrix multiplication : `(b,) x (b, d)`.

**Comment by GeoffNN** [comment]
#50, #60 made progress on this. @fabianp should we keep this open?

**Comment by fabianp** [comment]
closing
