### ISSUE TITLE
Implement partial_deriv method for Square Loss

### ISSUE THREAD

**Issue by GeoffNN** [openopt/copt#52]
Adding this as a todo for myself. This is needed for applying randomized methods (SAGA, SAG, Stochastic FW) on least squared models, such as Elastic Net, LASSO or Ridge regression.

**Comment by fabianp** [comment]
Thanks

**Comment by GeoffNN** [comment]
This was done in 469fffe85e12f92c16ece62d8649ab05bce91f30.
