### ISSUE TITLE
potential issue in SFW example

### ISSUE THREAD

**Issue by fabianp** [openopt/copt#55]
the FW gap doesn't go to zero in this example

http://openo.pt/copt/auto_examples/frank_wolfe/plot_sfw.html#sphx-glr-auto-examples-frank-wolfe-plot-sfw-py

I suspect there's a bug in the code

**Comment by GeoffNN** [comment]
The example works fine for `batch_size=1`. I suspect this is linked to #56.

**Comment by fabianp** [comment]
ncie catch

**Comment by GeoffNN** [comment]
Trouble starts at `batch_size=2`, so I think this is confirmed.

**Comment by GeoffNN** [comment]
Solved by a string of recent PRs, in particular #60, #62, #63
