### ISSUE TITLE
Refactor utils.py

### ISSUE THREAD

**Issue by GeoffNN** [openopt/copt#64]
Right now, utils.py contains objects for loss functions, constraints, and helper functions for speeding up computation. It should probably be split in 3 files: functions.py, constraints.py and utils.py.

Adding this as a general TODO, and up for discussion. (@fabianp )

**Comment by fabianp** [comment]
+1 except I would like to have more meaningful names than functions.py

**Comment by GeoffNN** [comment]
Maybe loss.py, constraint.py and utils.py?

**Comment by fabianp** [comment]
loss.py would be better for instance

**Comment by fabianp** [comment]
Indeed
