### ISSUE TITLE
Numba uses up all cores

### ISSUE THREAD

**Issue by GeoffNN** [openopt/copt#65]
It looks like numba uses up all available cores. It may be because of the `utils.sample_batches` function, with the `@njit(parallel=True)` decorator.

Any idea on how to limit this / performance impact?

**Comment by fabianp** [comment]
Isn't this a good thing?

**Comment by fabianp** [comment]
Some options on parallelization can also be set with environment variables https://numba.pydata.org/numba-doc/dev/reference/envvars.html

**Comment by GeoffNN** [comment]
Right, see this for info / setting it on the fly: https://numba.pydata.org/numba-doc/dev/user/threading-layer.html%23setting-the-number-of-threads.

Closing
