### ISSUE TITLE
Good practice on logging

### ISSUE THREAD

**Issue by GeoffNN** [openopt/copt#74]
What's the easiest / more practical way to log results, and keep them locally?
For now, we have the Trace objects, but no writing to file. Should this be part of a logging.py file, or should this functionality be something the user imports from another library?

**Comment by fabianp** [comment]
Would avoid having our own since many logging systems already exist, but I would definitely make it easy or provide examples on how to adapt existing frameworks to be used in copt (thinking tensorboard for example). What is your opinion?

**Comment by GeoffNN** [comment]
Todo for myself: try Cox https://github.com/MadryLab/cox
