### ISSUE TITLE
pairwise_lmo outputs 0 update_direction

### ISSUE THREAD

**Issue by GeoffNN** [openopt/copt#75]
This breaks the 'DR' step scheme, which is proportional to`1/norm(update_direction)`.
It happens even when we are not at the optimum.

In particular, where does [this](https://github.com/openopt/copt/blob/96d3c21bbd8f38b7a09fe21b8689b4d381ba1c7a/copt/constraint.py#L60) part of the code come from?

**Comment by GeoffNN** [comment]
Understood: it was because I was starting at iterate 0...

**Comment by GeoffNN** [comment]
This should be solved in the latest PR #83.

**Comment by fabianp** [comment]
awesome, thanks!
