### ISSUE TITLE
`pip install copt` yields `ModuleNotFoundError`. Same issue when installing from github

### ISSUE THREAD

**Issue by GeoffNN** [openopt/copt#91]

**Comment by fabianp** [comment]
I can't reproduce. Can you paste the full error and steps to reproduce (i.e., create fresh conda env etc.)

**Comment by fabianp** [comment]
thanks

**Comment by GeoffNN** [comment]
Closing the issue. It only happened from within the cloned `chop`  folder. No issue with a different working directory, so I'm attributing the problem to `chop`.
