### ISSUE TITLE
Master branch borked

### ISSUE THREAD

**Issue by gideonite** [openopt/copt#93]
Hi everyone,

I'm really sorry for this distraction, but I pushed to master by accident before I was ready. I think the way to solve this would be 
```
git checkout -b tmpbranch
git branch -D master
git checkout e5cb995  # this is fabian's last commit
git checkout -b master
git push -f
```
But I am hesitant to do this, especially if someone has unfortunately grabbed my commits by accident.

Any tips?

Sorry again and thanks for the help,
Gideon

@fabianp I think that you should be able to guide me here.

**Comment by fabianp** [comment]
no problem, I just forced push. should be good
